### PR TITLE
Allow to configure Octoprint with Cura 4.0.0

### PR DESCRIPTION
**Pull request by lynxis**
Cura changed the button styles name in https://github.com/Ultimaker/Cura/commit/1d33fe081fd30e257d9b0f5443288ad069b5f73c

### CODE REVIEW

**Comment by fieldOfView** [comment]
The master branch is currently behind the main branch which is 3.5. Use the 3.5 branch instead for now.

**Comment by fieldOfView** [comment]
I have updated the master branch, which is now functional with Cura 4.0. The 3.5 branch is still the default branch, and it is compatible with Cura 3.6, Cura 3.6 and Cura 4.0. 

Currently both the 3.5 and master branch are also compatible with the master branch of Cura, but there are some major changes in Cura master coming up that will require work in the OctoPrintPlugin master branch to remain compatible.

**Comment by lynxis** [comment]
@fieldOfView this PR is not fixed! The octoprint plugin still works with 4.0, but you can not configure it!
The button to get into the configuration menu on the printer page is not visible. Please take a look on the commit.

**Comment by fieldOfView** [comment]
It is fixed if you use the current master or 3.5 branch of the Cura-OctoPrintPlugin with the 4.0 branch of Cura (and 3.5 and 3.6, but currently not the master branch of Cura). There are a couple of thousand users of Cura 4.0 using the plugin. I am very aware of the changes to Cura between 3.5 and 4.0

Your fork of the master branch of this plugin is 13 commits behind my master branch. There are many changes in these 13 commits that fix compatibility with Cura 4.0.

Please check the logs, it will say why the plugin is not loading.

**Pull request closed without merging**
